name: example_flutter_bloc_wrapper
description: Sample used flutter bloc wrapper
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  auto_size_text: ^2.1.0
  flutter_bloc_wrapper:
    path: ../
  http: ^0.11.3+16
  http_middleware: ^1.0.0
  http_logger: ^1.0.0
  json_serializable: ^3.3.0
  json_annotation: ^3.0.1
  connectivity: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
     - locale/i18n_en.json
     - locale/i18n_ja.json



